FROM node:18.6-alpine as builder
WORKDIR /usr/naveenmraja
COPY ./package.json .
RUN npm install
COPY . .
ARG REACT_APP_CLOUDFRONT_DISTRIBUTION_URL
ENV REACT_APP_CLOUDFRONT_DISTRIBUTION_URL $REACT_APP_CLOUDFRONT_DISTRIBUTION_URL
RUN npm run build

FROM nginx
COPY --from=builder /usr/naveenmraja/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80